version: "3"
services:
  prod:
    build: .
    image: maximzasorin/highloadcup-1
    ports:
      - "3000:80"
    volumes:
      - ./data/train:/tmp/data
  dev:
    build: .
    image: maximzasorin/highloadcup-1
    ports:
      - "3000:80"
      - "56745:56745"
    volumes:
     - .:/usr/app
     - ./data/train:/tmp/data
    tty: true
    entrypoint:
      - /usr/bin/supervisord
      - -c
      - supervisord.dev.conf